adjust the order of install procedure

diff --git a/debian/openfde-1.0.7/debian/postinst b/debian/openfde-1.0.7/debian/postinst
--- a/debian/openfde-1.0.7/debian/postinst
+++ b/debian/openfde-1.0.7/debian/postinst
@@ -1,6 +1,12 @@
 #!/bin/bash
 
 #step 1 install fde
+if [ -e /usr/bin/fde_ctrl ];then
+	sudo mv /usr/bin/fde_ctrl /tmp/fde_ctrl&& sudo rm -rf /tmp/fde_ctrl
+fi
+if [ -e /usr/bin/fde_fs ];then
+	sudo mv /usr/bin/fde_fs /tmp/fde_fs && sudo rm -rf /tmp/fde_fs
+fi
 echo "Step 2: config environments"
 sudo tar -xf /usr/fde.tar -C /
 sudo sysctl -p
@@ -11,9 +17,6 @@ sudo rm -rf /usr/share/xsessions/mutter.desktop 1>/dev/null 2>&1
 
 echo "Step 3: load the image"
 if [ -e /usr/bin/waydroid ];then
-	sudo systemctl daemon-reload 1>/dev/null 2>&1
-	#sudo waydroid session stop 1>/dev/null 2>&1
-	#sudo systemctl stop waydroid-container 1>/dev/null 2>&1
 	sudo mv /var/lib/waydroid /tmp/waydroid && sudo rm -rf /tmp/waydroid
 	sudo mv /usr/share/waydroid-extra/images /tmp/images && rm -rf /tmp/images
 fi
@@ -43,6 +46,37 @@ sudo tar -xzf /usr/tigervnc.tar.gz -C /
 sudo pip3 install pyclip -i https://mirrors.aliyun.com/pypi/simple
 
 sudo tar -xf /usr/waydroid.tar -C /
+sudo systemctl daemon-reload 1>/dev/null 2>&1
+if [ ! -e /usr/bin/fde_wm ];then
+	source /etc/lsb-release
+	if [ "$DISTRIB_ID" = "Kylin" ];then
+
+sudo tar -xf /usr/waydroid_image.tar -C /
+
+if [ ! -e "/dev/fdeion" ];then
+	sudo mkdir vendorimg
+	sudo mount /usr/share/waydroid-extra/images/vendor.img vendorimg
+	if [ $? != 0 ];then
+		echo "Error: mount vendorimg failed"
+		sudo rm -rf /usr/fde.tar
+		sudo rm -rf /usr/waydroid.tar
+		sudo rm -rf /usr/fdeion.ko
+		sudo rm -rf /usr/waydroid_image.tar
+		sudo rm -rf /usr/tigervnc.tar.gz
+		exit 1
+	fi
+	sudo rm vendorimg/etc/vintf/manifest/android.hardware.graphics.allocator@4.0.img.xml 1>/dev/null 2>&1
+	sudo rm vendorimg/etc/vintf/manifest/android.hardware.graphics.mapper@4.0-passthrough.img.xml 1>/dev/null 2>&1
+	sudo rm vendorimg/etc/init/android.hardware.graphics.allocator@4.0-service.img.rc 1>/dev/null 2>&1
+	sudo umount vendorimg
+	sudo rmdir vendorimg 
+fi	
+
+sudo tar -xzf /usr/tigervnc.tar.gz -C /
+sudo pip3 install pyclip -i https://mirrors.aliyun.com/pypi/simple
+
+sudo tar -xf /usr/waydroid.tar -C /
+sudo systemctl daemon-reload 1>/dev/null 2>&1
 if [ ! -e /usr/bin/fde_wm ];then
 	source /etc/lsb-release
 	if [ "$DISTRIB_ID" = "Kylin" ];then
@@ -62,10 +96,14 @@ if [ $? != 0 ];then
 	exit 1
 fi
 
+sudo waydroid session stop 1>/dev/null 2>&1
+sudo systemctl stop waydroid-container 1>/dev/null 2>&1
 sudo sed -i "/fde.log/d" /etc/profile
 sudo sed -i  '$a \export LOG_FILE=/var/log/fde.log'  /etc/profile
-sudo touch /var/log/fde.log
-sudo chmod a+wr /var/log/fde.log
+if [ ! -e /var/log/fde.log ];then
+	sudo touch /var/log/fde.log
+	sudo chmod a+wr /var/log/fde.log
+fi
 sudo rm -rf /usr/fde.tar
 sudo rm -rf /usr/waydroid.tar
 sudo rm -rf /usr/waydroid_image.tar
