update to 2.0.3

diff --git a/debian/openfde14-2.0.3/debian/postinst b/debian/openfde14-2.0.3/debian/postinst
--- a/debian/openfde14-2.0.3/debian/postinst
+++ b/debian/openfde14-2.0.3/debian/postinst
@@ -47,17 +47,25 @@ sudo rm -rf /usr/openfde/waydroid.tar
 echo 50 >> /tmp/fde_installing_process
 
 sudo PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install  /usr/openfde/gbinder-python-1.0.0.tar.gz
+if [ $? != 0 ];then
+	echo "Error: Install OpenFDE failed"
+	exit 1
+fi
 echo 70 >> /tmp/fde_installing_process
 sudo rm -rf /usr/openfde/gbinder-python-1.0.0.tar.gz
 
-sudo PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install pyclip --find-links=/usr/lib/waydroid/wheel
+sudo PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install pyclip --no-index --find-links=/usr/lib/waydroid/wheel
 echo 80 >> /tmp/fde_installing_process
 source /etc/os-release
-sudo mv /usr/bin/fde_wm /tmp/fde_wm 1>/dev/null 2>&1 && sudo rm -rf /tmp/fde_wm 1>/dev/null 2>&1 
+if [ -e /usr/bin/fde_wm ];then
+	sudo mv /usr/bin/fde_wm /tmp/fde_wm 1>/dev/null 2>&1 && sudo rm -rf /tmp/fde_wm 1>/dev/null 2>&1
+fi
 if [ "$ID" = "kylin" ];then
 	sudo cp -a /usr/local/bin/mutter /usr/bin/fde_wm
 else
-	sudo cp -a /usr/bin/mutter /usr/bin/fde_wm
+	if [ "$ID" != "deepin" ];then
+		sudo cp -a /usr/bin/mutter /usr/bin/fde_wm
+	fi
 fi
 echo 85 >> /tmp/fde_installing_process
 sudo ldconfig
@@ -84,4 +92,4 @@ sudo chmod a+wr /var/log/fde.log
 echo 100 >> /tmp/fde_installing_process
 sudo rm -rf /usr/openfde
 sudo rm -rf  /tmp/fde_installing_process
-echo "Congratulations, the installation success, please logout and then relogin to the OpenFDE"
+echo "Congratulations, OpenFDE install successfully."
